### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [HaskellEmbedded/ion#1]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by Hodapp87** [comment]
Wow, the build is indeed [failing](https://hackage.haskell.org/package/ion-1.0.0.0/reports/1)... good catch:

```
cabal: Error: some packages failed to install:
ion-1.0.0.0 depends on ivory-0.1.0.3 which failed to install.
ivory-0.1.0.3 failed during the building phase. The exception was:
ExitFailure 1
ivory-backend-c-0.1.0.3 depends on ivory-0.1.0.3 which failed to install.
ivory-opts-0.1.0.3 depends on ivory-0.1.0.3 which failed to install.
```

I'll take a look at that today.

**Comment by Hodapp87** [comment]
hvr has uploaded docs for me. For now, however, the build is broken on GHC 8.0 as long as Ivory's released version is.
